nav-bar, dashboard and features modules-done
venkateshvhy/pinwheel pull request #1
Opened 2024-12-30 13:50 UTC by venkateshvhy

2025-01-01 06:30 UTC, Venkatesh-VH requested changes
Please do make the necessary changes mentioned in the comments

2025-01-01 06:30 UTC, Venkatesh-VH commented on common/PW-Button.vue
> +  label: String,
this is not the right way of defining types when using setup lang="ts"

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Features.vue
> +      src="../assets/img/feature-shape.svg"
try to store all images in a place as enum or object and then use it

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Carosol.vue
> +<script lang="ts" setup>
order should be <script setup lang="ts">

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Carosol.vue
> +import { Swiper, SwiperSlide } from 'swiper/vue';
use prettier to always make string to be double quotes instead of single quote

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Carosol.vue
> +import Henry from '../assets/img/henry.png';
images/icon can be stored in a .ts file and then import it

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Carosol.vue
> +      :slidesPerGroup="1"
props should be kebab cased like :slides-per-group="1"

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Carosol.vue
> +  background: #ffffff;
it would be better to declare reusable color or fonts as a css variable and the use it using var()

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/DownloadThemeContent.vue
> +            style="font-family: Merriweather, sans-serif; --tw-text-opacity: 1;"
main font can be declared as font family in main css file

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/Features.vue
> +          <p class="text-[#888] desc md:text-center lg:text-start">
whenver using hexcode make sure they are 6 characters after "#"

2025-01-01 06:30 UTC, Venkatesh-VH commented on pages/index.vue
> +<style scoped>
if style or script is not used in a SFC file then no need to declare them

2025-01-01 06:30 UTC, Venkatesh-VH commented on components/VideoTestimonial.vue
> +            <img v-if="!isVideoPlaying" src="../assets/img/collaborator-shap.svg" alt="" class="absolute -z-10 -right-[-1.8rem] -bottom-[-1.4rem]" style="right: -1.8rem; bottom: -1.4rem;">
always provide a description in alt tag

2025-01-01 06:52 UTC, venkateshvhy commented
Hi Venkatesh,
Thank you for reviewing the pull request and providing your feedback. I will go ahead and make the necessary changes as per the comments you mentioned.


Thanks & Regards,



[A picture containing line chart  Description automatically generated]

Venkatesh Bandaru
Software Developer | VHypotenuse Pvt Ltd
M: +91 - 939-849-5139
E: ***@***.******@***.***> W: vhypotenuse.com<https://vhypotenuse.com/>

This e-mail communication may contain confidential or legally privileged information that is intended only for the individual or entity named in the e-mail address. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution, or reliance upon the contents of this e-mail is strictly prohibited. If you have received this e-mail communication by mistake, please notify the sender, so that sender can arrange for proper delivery, and then please delete the message from your mailbox.

________________________________
From: Venkatesh-VH ***@***.***>
Sent: 01 January 2025 12:00
To: venkateshvhy/pinwheel ***@***.***>
Cc: venkateshvhy ***@***.***>; Author ***@***.***>
Subject: Re: [venkateshvhy/pinwheel] nav-bar, dashboard and features modules-done (PR #1)


@Venkatesh-VH requested changes on this pull request.

Please do make the necessary changes mentioned in the comments

________________________________

In common/PW-Button.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1899900345>:

> @@ -0,0 +1,60 @@
+<script setup lang="ts">
+defineProps({
+  label: String,


this is not the right way of defining types when using setup lang="ts"

________________________________

In components/Features.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1899900482>:

> +    label: "Focus Mode",
+    description: "Lorem ipsum dolor sit amet consectetur, adipiscing elit.",
+    icon: "heroicons:viewfinder-circle-solid",
+  },
+  {
+    label: "Family Link",
+    description: "Lorem ipsum dolor sit amet consectetur, adipiscing elit.",
+    icon: "heroicons:link",
+  },
+];
+</script>
+
+<template>
+  <div class="relative px-2 py-16">
+    <img
+      src="../assets/img/feature-shape.svg"


try to store all images in a place as enum or object and then use it

________________________________

In components/Carosol.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900331338>:

> @@ -0,0 +1,229 @@
+<script lang="ts" setup>


order should be <script setup lang="ts">

________________________________

In components/Carosol.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900331443>:

> @@ -0,0 +1,229 @@
+<script lang="ts" setup>
+import { Swiper, SwiperSlide } from 'swiper/vue';


use prettier to always make string to be double quotes instead of single quote

________________________________

In components/Carosol.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900331548>:

> @@ -0,0 +1,229 @@
+<script lang="ts" setup>
+import { Swiper, SwiperSlide } from 'swiper/vue';
+import { Pagination, Autoplay } from 'swiper/modules';
+import 'swiper/css';
+import 'swiper/css/pagination';
+
+import Henry from '../assets/img/henry.png';


images/icon can be stored in a .ts file and then import it

________________________________

In components/Carosol.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900331642>:

> +    image: Cooper,
+    rating: 4,
+  },
+];
+
+const swiperModules = [Pagination, Autoplay];
+</script>
+
+<template>
+  <div>
+    <Swiper
+      :modules="swiperModules"
+      :slides-per-view="3"
+      :space-between="30"
+      :loop="true"
+      :slidesPerGroup="1"


props should be kebab cased like :slides-per-group="1"

________________________________

In components/Carosol.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900331878>:

> +              :class="{ 'filled-star': star <= testimonial.rating }"
+              class="star"
+            >
+              ★
+            </span>
+          </div>
+        </div>
+      </SwiperSlide>
+    </Swiper>
+    <div class="custom-pagination"></div>
+  </div>
+</template>
+
+<style scoped>
+.testimonial-card {
+  background: #ffffff;


it would be better to declare reusable color or fonts as a css variable and the use it using var()

________________________________

In components/DownloadThemeContent.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900332002>:

> @@ -9,8 +9,8 @@ import PWButton from "~/common/PW-Button.vue";
         <!-- Left content -->
         <div class="max-w-xl space-y-6">
           <h1
-            class="text-[2.9rem] font-bold text-[#222222] leading-tight"
-            style="font-family: 'Merriweather !important;"
+            class="text-[2.3rem] font-bold text-[#222222] leading-tight md:text-[2.9rem]"
+            style="font-family: Merriweather, sans-serif; --tw-text-opacity: 1;"


main font can be declared as font family in main css file

________________________________

In components/Features.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900332062>:

>            >
             The Highlighting Part Of Our Solution
           </h2>
         </div>
         <div class="lg:max-w-md">
-          <p class="text-gray-600 desc md:text-center lg:text-start">
+          <p class="text-[#888] desc md:text-center lg:text-start">


whenver using hexcode make sure they are 6 characters after "#"

________________________________

In pages/index.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900332191>:

>  </template>

-<style scoped></style>
+
+<style scoped>


if style or script is not used in a SFC file then no need to declare them

________________________________

In components/VideoTestimonial.vue<https://github.com/venkateshvhy/pinwheel/pull/1#discussion_r1900332272>:

> +            >
+              <div class="relative">
+                <div
+                  class="absolute rounded-full -inset-4 bg-orange-500/30 animate-ping"
+                ></div>
+                <svg
+                  class="w-8 h-8 text-white relative z-10 translate-x-0.5"
+                  fill="currentColor"
+                  viewBox="0 0 24 24"
+                >
+                  <path d="M8 5v14l11-7z" />
+                </svg>
+              </div>
+            </button>
+          </div>
+            <img v-if="!isVideoPlaying" src="../assets/img/collaborator-shap.svg" alt="" class="absolute -z-10 -right-[-1.8rem] -bottom-[-1.4rem]" style="right: -1.8rem; bottom: -1.4rem;">


always provide a description in alt tag

—
Reply to this email directly, view it on GitHub<https://github.com/venkateshvhy/pinwheel/pull/1#pullrequestreview-2526141452>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A7FOR37CQEA3YYLEEYMYIQL2IODQRAVCNFSM6AAAAABUMCQS3WVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRWGE2DCNBVGI>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-01-02 11:49 UTC, Venkatesh-VH requested changes

2025-01-02 11:49 UTC, Venkatesh-VH commented on components/VideoTestimonial.vue
> +        <p class="text-[#888888] desc">
kindly make the color code as css variables and reuse it. I see #888888 and #fffffff being directly used without css variable

2025-01-04 04:01 UTC, merged